const STORAGE_KEY = 'heatbook-timers-v1';
const foodImages = [
  ['assets/food/icons8-poultry-leg-96.png', 'Chicken'], ['assets/food/icons8-whole-fish-96.png', 'Fish'],
  ['assets/food/icons8-broccoli-96.png', 'Broccoli'], ['assets/food/icons8-sweet-potato-96.png', 'Sweet potato'],
  ['assets/food/icons8-potato-96.png', 'Potato'], ['assets/food/icons8-carrot-96.png', 'Carrots'],
  ['assets/food/icons8-beef-96.png', 'Beef'], ['assets/food/icons8-zucchini-96.png', 'Zucchini'],
  ['assets/food/icons8-rice-96.png', 'Rice'], ['assets/food/icons8-eggs-96.png', 'Eggs'],
];
const methods = [['air', 'Air fryer'], ['oven_gen', 'Oven'], ['skillet', 'Pan'], ['soup_kitchen', 'Boil'], ['outdoor_grill', 'Grill']];
const starters = [
  { title: 'Chicken', subtitle: 'Cubes', image: 'assets/food/icons8-poultry-leg-96.png', method: 'air', temperature: 400, timeMin: 8, timeMax: 12 },
  { title: 'Fish', subtitle: 'Fillet', image: 'assets/food/icons8-whole-fish-96.png', method: 'oven_gen', temperature: 425, timeMin: 12, timeMax: 15 },
  { title: 'Broccoli', subtitle: 'Florets', image: 'assets/food/icons8-broccoli-96.png', method: 'soup_kitchen', temperature: 212, timeMin: 5, timeMax: 7 },
  { title: 'Sweet potato', subtitle: 'Wedges', image: 'assets/food/icons8-sweet-potato-96.png', method: 'air', temperature: 400, timeMin: 14, timeMax: 18 }
];
const list = document.querySelector('#timer-list'), empty = document.querySelector('#empty-state'), dialog = document.querySelector('#timer-dialog'), form = document.querySelector('#timer-form');
const imageDialog = document.querySelector('#image-dialog'), methodDialog = document.querySelector('#method-dialog'), resetDialog = document.querySelector('#reset-dialog');
const fields = Object.fromEntries([...form.elements].filter(x => x.name).map(x => [x.name, x]));
let timers = load(), editingIndex = null;
function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(saved) ? saved : structuredClone(starters); } catch { return structuredClone(starters); } }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(timers)); }
function syncPickers() { const imageName = foodImages.find(([path]) => path === fields.image.value)?.[1] || 'Food'; document.querySelector('#selected-image').src = fields.image.value; document.querySelector('#selected-image').alt = imageName; const [, methodName] = methods.find(([icon]) => icon === fields.method.value) || methods[0]; document.querySelector('#selected-method-icon').textContent = fields.method.value; document.querySelector('#selected-method-label').textContent = methodName; document.querySelectorAll('.image-option').forEach(option => option.setAttribute('aria-pressed', String(option.dataset.value === fields.image.value))); document.querySelectorAll('.method-option').forEach(option => option.setAttribute('aria-pressed', String(option.dataset.value === fields.method.value))); }
function populatePickers() { document.querySelector('#image-options').innerHTML = foodImages.map(([path, name]) => `<button type="button" class="image-option" data-value="${path}" aria-pressed="false"><img src="${path}" alt="" /><span>${name}</span></button>`).join(''); document.querySelector('#method-options').innerHTML = methods.map(([icon, name]) => `<button type="button" class="method-option" data-value="${icon}" aria-pressed="false"><span class="material-symbols-rounded">${icon}</span><span>${name}</span></button>`).join(''); document.querySelectorAll('.image-option').forEach(option => option.addEventListener('click', () => { fields.image.value = option.dataset.value; fields.title.value = foodImages.find(([path]) => path === fields.image.value)?.[1] || ''; syncPickers(); imageDialog.close(); })); document.querySelectorAll('.method-option').forEach(option => option.addEventListener('click', () => { fields.method.value = option.dataset.value; syncPickers(); methodDialog.close(); })); }
function render() { list.innerHTML = ''; empty.hidden = timers.length > 0; timers.forEach((timer, index) => { const card = document.querySelector('#timer-template').content.cloneNode(true); const row = card.querySelector('.timer-card'); card.querySelector('.food-image').src = timer.image; card.querySelector('.food-image').alt = timer.title; card.querySelector('.timer-title').textContent = timer.title; card.querySelector('.timer-subtitle').textContent = timer.subtitle || '—'; card.querySelector('.method-icon').textContent = timer.method; card.querySelector('.temperature').textContent = `${timer.temperature}°F`; card.querySelector('.time-range').textContent = `${timer.timeMin}–${timer.timeMax} min`; row.addEventListener('click', () => openDialog(index)); row.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openDialog(index); } }); list.append(card); }); }
function openDialog(index = null) { editingIndex = index; const isEdit = index !== null; document.querySelector('#dialog-title').textContent = isEdit ? 'Edit timer' : 'Add timer'; document.querySelector('#delete-button').hidden = !isEdit; form.reset(); if (isEdit) Object.entries(timers[index]).forEach(([name, value]) => { if (fields[name]) fields[name].value = value; }); else { fields.image.value = foodImages[0][0]; fields.method.value = methods[0][0]; } syncPickers(); dialog.showModal(); }
function closeDialog() { dialog.close(); editingIndex = null; }
document.querySelector('#add-button').addEventListener('click', () => openDialog()); document.querySelector('#close-dialog').addEventListener('click', closeDialog); document.querySelector('#cancel-button').addEventListener('click', closeDialog);
document.querySelector('#image-picker-button').addEventListener('click', () => imageDialog.showModal()); document.querySelector('#method-picker-button').addEventListener('click', () => methodDialog.showModal()); document.querySelectorAll('.close-picker').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
document.querySelector('#delete-button').addEventListener('click', () => { if (editingIndex !== null) { timers.splice(editingIndex, 1); save(); render(); closeDialog(); } });
document.querySelector('#reset-data').addEventListener('click', () => resetDialog.showModal());
document.querySelector('#cancel-reset').addEventListener('click', () => resetDialog.close());
document.querySelector('#confirm-reset').addEventListener('click', () => { timers = structuredClone(starters); save(); render(); resetDialog.close(); });
form.addEventListener('submit', event => { event.preventDefault(); const timer = { title: fields.title.value.trim(), subtitle: fields.subtitle.value.trim(), image: fields.image.value, method: fields.method.value, temperature: Number(fields.temperature.value), timeMin: Number(fields.timeMin.value), timeMax: Number(fields.timeMax.value) }; if (timer.timeMax < timer.timeMin) { fields.timeMax.setCustomValidity('The ending time must be greater than or equal to the starting time.'); fields.timeMax.reportValidity(); return; } fields.timeMax.setCustomValidity(''); if (editingIndex === null) timers.push(timer); else timers[editingIndex] = timer; save(); render(); closeDialog(); });
populatePickers(); render();
