const STORAGE_KEY = 'heatbook-timers-v1';
const foodImages = [
  ['assets/food/icons8-poultry-leg-96.png', 'Chicken'], ['assets/food/icons8-whole-fish-96.png', 'Fish'],
  ['assets/food/icons8-broccoli-96.png', 'Broccoli'], ['assets/food/icons8-sweet-potato-96.png', 'Sweet potato'],
  ['assets/food/icons8-potato-96.png', 'Potato'], ['assets/food/icons8-carrot-96.png', 'Carrots'],
  ['assets/food/icons8-beef-96.png', 'Beef'], ['assets/food/icons8-zucchini-96.png', 'Zucchini'],
  ['assets/food/icons8-rice-96.png', 'Rice'], ['assets/food/icons8-eggs-96.png', 'Eggs'],
];
const methods = [['air', 'Air fryer'], ['oven_gen', 'Oven'], ['skillet', 'Pan'], ['soup_kitchen', 'Boil'], ['outdoor_grill', 'Grill']];
const starters = [
  { title: 'Chicken', subtitle: 'Cubes', image: 'assets/food/icons8-poultry-leg-96.png', method: 'air', temperature: 400, timeMin: 8, timeMax: 12 },
  { title: 'Fish', subtitle: 'Fillet', image: 'assets/food/icons8-whole-fish-96.png', method: 'oven_gen', temperature: 425, timeMin: 12, timeMax: 15 },
  { title: 'Broccoli', subtitle: 'Florets', image: 'assets/food/icons8-broccoli-96.png', method: 'soup_kitchen', temperature: 212, timeMin: 5, timeMax: 7 },
  { title: 'Sweet potato', subtitle: 'Wedges', image: 'assets/food/icons8-sweet-potato-96.png', method: 'air', temperature: 400, timeMin: 14, timeMax: 18 }
];
const list = document.querySelector('#timer-list'), empty = document.querySelector('#empty-state'), dialog = document.querySelector('#timer-dialog'), form = document.querySelector('#timer-form');
const imageDialog = document.querySelector('#image-dialog'), methodDialog = document.querySelector('#method-dialog'), resetDialog = document.querySelector('#reset-dialog'), durationDialog = document.querySelector('#duration-dialog');
const fields = Object.fromEntries([...form.elements].filter(x => x.name).map(x => [x.name, x]));
let timers = load(), editingIndex = null, durationTarget = null, durationHours = 0, durationMinutes = 0, durationMode = 'minutes', clockDragging = false;
function load() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return Array.isArray(saved) ? saved : structuredClone(starters); } catch { return structuredClone(starters); } }
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(timers)); }
function syncPickers() { const imageName = foodImages.find(([path]) => path === fields.image.value)?.[1] || 'Food'; document.querySelector('#selected-image').src = fields.image.value; document.querySelector('#selected-image').alt = imageName; const [, methodName] = methods.find(([icon]) => icon === fields.method.value) || methods[0]; document.querySelector('#selected-method-icon').textContent = fields.method.value; document.querySelector('#selected-method-label').textContent = methodName; document.querySelectorAll('.image-option').forEach(option => option.setAttribute('aria-pressed', String(option.dataset.value === fields.image.value))); document.querySelectorAll('.method-option').forEach(option => option.setAttribute('aria-pressed', String(option.dataset.value === fields.method.value))); }
function formatDuration(total) { const minutes = Number(total); if (!Number.isFinite(minutes) || minutes < 0 || total === '') return 'Select time'; const hours = Math.floor(minutes / 60), remainder = minutes % 60; if (!hours) return `${remainder} min`; if (!remainder) return `${hours} hr`; return `${hours} hr ${remainder} min`; }
function syncDurationFields() { [['timeMin', '#time-min-display'], ['timeMax', '#time-max-display']].forEach(([name, selector]) => { const display = document.querySelector(selector), button = display.closest('.duration-field'); display.textContent = formatDuration(fields[name].value); button.classList.toggle('is-empty', fields[name].value === ''); }); }
function renderDurationClock() { const minuteMode = durationMode === 'minutes', selected = minuteMode ? durationMinutes : durationHours, values = minuteMode ? Array.from({ length: 12 }, (_, index) => index * 5) : Array.from({ length: 12 }, (_, index) => index); document.querySelector('#duration-hours-value').textContent = String(durationHours).padStart(2, '0'); document.querySelector('#duration-minutes-value').textContent = String(durationMinutes).padStart(2, '0'); document.querySelector('#duration-hours').classList.toggle('active', !minuteMode); document.querySelector('#duration-minutes').classList.toggle('active', minuteMode); const face = document.querySelector('#clock-face'); face.setAttribute('aria-label', minuteMode ? 'Minute clock face' : 'Hour clock face'); document.querySelector('#clock-hand').style.setProperty('--hand-angle', `${selected * (minuteMode ? 6 : 30)}deg`); document.querySelector('#clock-numbers').innerHTML = values.map(value => `<button type="button" class="clock-number${value === selected ? ' selected' : ''}" data-clock-value="${value}" style="--angle:${value * (minuteMode ? 6 : 30)}deg" aria-label="${value} ${minuteMode ? 'minutes' : 'hours'}">${minuteMode ? String(value).padStart(2, '0') : value}</button>`).join(''); document.querySelectorAll('.clock-number').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); setDurationValue(Number(button.dataset.clockValue)); })); }
function setDurationValue(value) { if (durationMode === 'minutes') durationMinutes = value % 60; else durationHours = value % 12; renderDurationClock(); }
function setDurationFromPointer(event) { const face = document.querySelector('#clock-face'), rect = face.getBoundingClientRect(), x = event.clientX - rect.left - rect.width / 2, y = event.clientY - rect.top - rect.height / 2, degrees = (Math.atan2(y, x) * 180 / Math.PI + 90 + 360) % 360; setDurationValue(Math.round(degrees / (durationMode === 'minutes' ? 6 : 30)) % (durationMode === 'minutes' ? 60 : 12)); }
function openDurationPicker(target) { durationTarget = target; const total = Math.max(0, Math.min(719, Number(fields[target].value) || 0)); durationHours = Math.floor(total / 60); durationMinutes = total % 60; durationMode = 'minutes'; renderDurationClock(); durationDialog.showModal(); document.querySelector('#duration-minutes').focus(); }
function populatePickers() { document.querySelector('#image-options').innerHTML = foodImages.map(([path, name]) => `<button type="button" class="image-option" data-value="${path}" aria-pressed="false"><img src="${path}" alt="" /><span>${name}</span></button>`).join(''); document.querySelector('#method-options').innerHTML = methods.map(([icon, name]) => `<button type="button" class="method-option" data-value="${icon}" aria-pressed="false"><span class="material-symbols-rounded">${icon}</span><span>${name}</span></button>`).join(''); document.querySelectorAll('.image-option').forEach(option => option.addEventListener('click', () => { fields.image.value = option.dataset.value; fields.title.value = foodImages.find(([path]) => path === fields.image.value)?.[1] || ''; syncPickers(); imageDialog.close(); })); document.querySelectorAll('.method-option').forEach(option => option.addEventListener('click', () => { fields.method.value = option.dataset.value; syncPickers(); methodDialog.close(); })); }
function render() { list.innerHTML = ''; empty.hidden = timers.length > 0; timers.forEach((timer, index) => { const card = document.querySelector('#timer-template').content.cloneNode(true); const row = card.querySelector('.timer-card'); card.querySelector('.food-image').src = timer.image; card.querySelector('.food-image').alt = timer.title; card.querySelector('.timer-title').textContent = timer.title; card.querySelector('.timer-subtitle').textContent = timer.subtitle || '—'; card.querySelector('.method-icon').textContent = timer.method; card.querySelector('.temperature').textContent = `${timer.temperature}°F`; card.querySelector('.time-range').textContent = `${timer.timeMin}–${timer.timeMax} min`; row.addEventListener('click', () => openDialog(index)); row.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openDialog(index); } }); list.append(card); }); }
function openDialog(index = null) { editingIndex = index; const isEdit = index !== null; document.querySelector('#dialog-title').textContent = isEdit ? 'Edit timer' : 'Add timer'; document.querySelector('#delete-button').hidden = !isEdit; form.reset(); if (isEdit) Object.entries(timers[index]).forEach(([name, value]) => { if (fields[name]) fields[name].value = value; }); else { fields.image.value = foodImages[0][0]; fields.method.value = methods[0][0]; fields.timeMin.value = ''; fields.timeMax.value = ''; } syncPickers(); syncDurationFields(); dialog.showModal(); }
function closeDialog() { dialog.close(); editingIndex = null; }
document.querySelector('#add-button').addEventListener('click', () => openDialog()); document.querySelector('#close-dialog').addEventListener('click', closeDialog); document.querySelector('#cancel-button').addEventListener('click', closeDialog);
document.querySelector('#image-picker-button').addEventListener('click', () => imageDialog.showModal()); document.querySelector('#method-picker-button').addEventListener('click', () => methodDialog.showModal()); document.querySelectorAll('.close-picker').forEach(button => button.addEventListener('click', () => button.closest('dialog').close()));
document.querySelectorAll('[data-duration-field]').forEach(button => button.addEventListener('click', () => openDurationPicker(button.dataset.durationField)));
document.querySelector('#duration-hours').addEventListener('click', () => { durationMode = 'hours'; renderDurationClock(); });
document.querySelector('#duration-minutes').addEventListener('click', () => { durationMode = 'minutes'; renderDurationClock(); });
document.querySelector('#cancel-duration').addEventListener('click', () => durationDialog.close());
document.querySelector('#confirm-duration').addEventListener('click', () => { if (durationTarget) { fields[durationTarget].value = durationHours * 60 + durationMinutes; document.querySelector(`[data-duration-field="${durationTarget}"]`).removeAttribute('aria-invalid'); } syncDurationFields(); durationDialog.close(); });
document.querySelector('#clock-face').addEventListener('pointerdown', event => { clockDragging = true; event.currentTarget.setPointerCapture(event.pointerId); setDurationFromPointer(event); });
document.querySelector('#clock-face').addEventListener('pointermove', event => { if (clockDragging) setDurationFromPointer(event); });
document.querySelector('#clock-face').addEventListener('pointerup', event => { clockDragging = false; event.currentTarget.releasePointerCapture(event.pointerId); });
document.querySelector('#clock-face').addEventListener('pointercancel', () => { clockDragging = false; });
document.querySelector('#delete-button').addEventListener('click', () => { if (editingIndex !== null) { timers.splice(editingIndex, 1); save(); render(); closeDialog(); } });
document.querySelector('#reset-data').addEventListener('click', () => resetDialog.showModal());
document.querySelector('#cancel-reset').addEventListener('click', () => resetDialog.close());
document.querySelector('#confirm-reset').addEventListener('click', () => { timers = structuredClone(starters); save(); render(); resetDialog.close(); });
form.addEventListener('submit', event => { event.preventDefault(); const timer = { title: fields.title.value.trim(), subtitle: fields.subtitle.value.trim(), image: fields.image.value, method: fields.method.value, temperature: Number(fields.temperature.value), timeMin: Number(fields.timeMin.value), timeMax: Number(fields.timeMax.value) }; if (timer.timeMax < timer.timeMin) { const maxButton = document.querySelector('[data-duration-field="timeMax"]'); maxButton.setAttribute('aria-invalid', 'true'); maxButton.focus(); return; } document.querySelector('[data-duration-field="timeMax"]').removeAttribute('aria-invalid'); if (editingIndex === null) timers.push(timer); else timers[editingIndex] = timer; save(); render(); closeDialog(); });
populatePickers(); render();
